### PR TITLE
Handle IPv4ToIPv6 Mapped Addresses when checking known proxies/networks

### PR DESCRIPTION
**Pull request by SebastianC**
Un-Map IPv4-to-IPv6-Mapped ips before comparing to known proxies/networks.

Addresses #358

### CODE REVIEW

**Comment by Tratcher** [comment]
As discussed on the issue, this needs to check both versions of the IP.

**Comment by Tratcher** [comment]
The code looks good. Can you add some tests?

**Comment by SebastianC** [comment]
I would love to, but running into the following issue when I go to run unit tests:

```
Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.2.0-preview1-26618-02' was not found.
```

Downloading the current preview version from https://www.microsoft.com/net/download/dotnet-core/2.2 gives me a different version:
```
> dotnet --version
2.2.100-preview1-009349
```

Do you know how I can go about resolving this?
@Tratcher

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Home/wiki/Building-from-source

**Pull request merged**
