### PR TITLE
Added more GZIP compressable MIME types

### PR DESCRIPTION
**Pull request by RehanSaeed**
The MIME type list for what can be compressed is a bit basic. There are several other formats which can be compressed, including images and font file formats.

### CODE REVIEW

**Comment by Tratcher** [comment]
Please open an issue with the recommended types and justifications for each. This was intentionally not an exhaustive list to start with. Everybody is going to have their own types they want and we don't want to maintain a huge list, only types that more than 50-80% of apps will use.

What did you think of the API for adding your own types in Startup?
https://github.com/aspnet/BasicMiddleware/blob/dev/samples/ResponseCompressionSample/Startup.cs#L28

**Comment by davidfowl** [comment]
> What did you think of the API for adding your own types in Startup?
https://github.com/aspnet/BasicMiddleware/blob/dev/samples/ResponseCompressionSample/Startup.cs#L28

That API is pretty awful. Especially because of the lack of append... Though even with append it's strange to use `IEnumerable<T>` that way. Why isn't the list mutable (like MVC's model binders)

**Comment by RehanSaeed** [comment]
Agreed that a mutable collection would have been more natural, it's what I instinctively looked for but looking at the source found it to be an array. I've raised this https://github.com/aspnet/BasicMiddleware/issues/182 issue with my justifications for each MIME type.

**Comment by Tratcher** [comment]
Mutable collections can't be added to in inline constructors.

**Comment by muratg** [comment]
@glennc will be considering the work required and will use https://github.com/aspnet/BasicMiddleware/issues/182 to track the work.

Closing this one. Thanks @RehanSaeed!

**Pull request closed without merging**
