### PR TITLE
Set 2.1 baselines

### PR DESCRIPTION
**Pull request by ryanbrandenburg**

### CODE REVIEW

**Comment by ryanbrandenburg** [comment]
An API has been [removed](https://dotnet.visualstudio.com/public/public%20Team/_build/results?buildId=1762&view=logs) between 2.1 and dev. @Tratcher was this breaking changes intended/approved?

```
The following types have one or more members removed from them.

public class Microsoft.AspNetCore.HttpsPolicy.HstsMiddleware
    public .ctor(Microsoft.AspNetCore.Http.RequestDelegate next, Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.HttpsPolicy.HstsOptions> options)
    
Following is the list of exclusions that either need to be added to the list of breaking changes, or the breaking changes themselves need to be reverted:
   [
     {
       "TypeId": "public class Microsoft.AspNetCore.HttpsPolicy.HstsMiddleware",
       "MemberId": "public .ctor(Microsoft.AspNetCore.Http.RequestDelegate next, Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.HttpsPolicy.HstsOptions> options)",
       "Kind": "Removal"
     }
   ]
```

**Comment by jkotalik** [comment]
This was not intentional. We need to re-add the api.

**Comment by Tratcher** [comment]
Ah, https://github.com/aspnet/BasicMiddleware/commit/77c9bc38f914b78f53fd5828c68c4ceca44bd841#diff-a9c581affe19c089a2458ae1f14557b5.
A parameter was added to the constructor. We need to add back the old constructor.

**Comment by Tratcher** [comment]
Filed https://github.com/aspnet/BasicMiddleware/issues/339

**Pull request merged**
